# -*- coding: utf-8 -*-
"""docai.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Fn_8807w4W7STrSJhHN4ypaWuCvL9v7
"""

!pip install openai
import openai

openai.api_key = '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'

def chat_with_gpt(prompt):
  response = openai.ChatCompletion.create(
      model='gpt-3.5-turbo',
      messages=[{'role': 'user', 'content': prompt}]
  )

  return response.choices[0].message.content.strip()

print("Welcome to the CatDoc! How can i assist you.")
print("Type 'quit' to leave the conversation.")

if __name__ == "__main__":
  while True:
    user_input = input('You: ')
    if user_input.lower() in ['quit', 'exit', 'bye']:
      break

    response = chat_with_gpt(user_input)
    print('CatDoc: ', response)